version: 2
jobs:
  # build: Workflowを試しに使ってみるためにコメントアウト
  build_and_test: # workflowから呼び出し
    docker: # ベースとなるDocker imageを指定
      - image: python:3
    environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo # Time Zoneを指定
    #working_directory: デフォルトが`~/project/`
    steps:
      - checkout
      - run:
          name: analyze by SonarQube
          command: |
              ls -la
              bash .circleci/analyze-sonarqube.sh
      - run: mkdir htmlcov # テストコード置き場

      # requirements.txtに変更がなければ、以前作成したPython仮想環境を復元
      # save_cacheで指定したkeyで保存したファイルをダウンロードできる。
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
         name: Install dependencies
         command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Python仮想環境を保管
      # pathsで設定した内容をkeyの名前で保存できる。
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test

      # テスト結果の成果物を保存するパス
      - store_artifacts:
          path: htmlcov/

workflows: # 試しに入れてみた。
  version: 2
  build_and_test: # workflow名
    jobs:
      - build_and_test