version: 2
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout

      # requirements.txtに変更がなければ、以前作成したPython仮想環境を復元
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
         command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Python仮想環境を保管
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: Run tests
          command: python manage.py test stocks

      - store_artifacts:
          path: test-reports
          destination: test-reports